baemin/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('client.urls')),
    url(r'^partner/', include('partner.urls')),
    url(r'^admin/', admin.site.urls),
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

client/models.py
from django.db import models
from django.contrib.auth.models import User
from partner.models import Menu

# Create your models here.
class Client(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(
        max_length=50,
        verbose_name="고객 이름",
    )

class Order(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    address = models.CharField(
        max_length=100,
        verbose_name="주소",
    )
    created_at = models.DateTimeField(auto_now_add=True)

    items = models.ManyToManyField(
        Menu,
        through='OrderItem',
        through_fields=('order', 'menu'),
    )

class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    menu = models.ForeignKey(Menu, on_delete=models.CASCADE)
    count = models.PositiveSmallIntegerField()

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=11; IE=10; IE=8; IE7; IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>{% block title %}sample{% endblock %}</title>
    <!-- <title /> -->
    <link rel="stylesheet" href='{% static "css/lib/bootstrap.min.css" %}'>
    <link rel="stylesheet" href='{% static "css/lib/font-awesome.min.css" %}'>
    <link rel="stylesheet" href='{% static "css/base.css" %}'>
</head>
<body>
  {% block body %}{% endblock %}
  <script src='{% static "js/lib/bootstrap.min.js" %}'></script>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-134102600-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-134102600-1');
  </script>
</body>
</html>

templates/edit_info.html
{% extends "base.html" %}
{% block title %}baemin{% endblock %}
{% block body %}
{% include "navbar.html" %}
<div class="container">
  정보를 수정해주세요.
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-default">저장하기</button>
      </form>
    </div>
  </div>
</div>
{% endblock %}

templates/index.html
{% extends "base.html" %}
{% block title %}baemin{% endblock %}
{% block body %}
{% include "navbar.html" %}
<div class="container">
  {% if user.is_authenticated %}
    {% if user.partner %}
      <div class="row">
        <div class="col-sm-6 col-sm-offset-3">
          <h2>환영합니다.</h2>
          <table class="table">
            <tr>
              <th>
                업체이름
              </th>
              <td>
              {{ user.partner.name }}
              </td>
            </tr>
            <tr>
              <th>
                연락처
              </th>
              <td>
              {{ user.partner.contact }}
              </td>
            </tr>
            <tr>
              <th>
                주소
              </th>
              <td>
              {{ user.partner.address }}
              </td>
            </tr>
            <tr>
              <th>
                업체소개
              </th>
              <td>
              {{ user.partner.description }}
              </td>
            </tr>
          </table>
          <a href="/partner/edit/">
            <button class="btn btn-default btn-block">
              수정하기
            </button>
          </a>
        </div>
      </div>
    {% else %}
      추가정보를 입력하세요
          <form action="" method="post">
            {% csrf_token %}
            <!-- <div class="form-group">
              <input type="text" name="name" class="form-control">
            </div>
            <div>
              <input type="text" name="contact">
            </div>
            <div>
              <input type="text" name="address">
            </div>
            <div>
              <input type="text" name="description">
            </div> -->
            {{ form.as_p }}
            <button class="btn btn-default">저장하기</button>
          </form>
    {% endif %}
  {% else %}
  <div>로그인 해주세요</div>
  {% endif %}
</div>
{% endblock %}

templates/login.html
{% extends "base.html" %}
{% block title %}baemin signup{% endblock %}
{% block body %}
<div class="container">
  <form method="post" action="" class="form-signin">
    {% csrf_token %}
    <h2 class="form-signin-heading">please log in</h2>
    <input type="text" name="username"
      class="form-control" placeholder="Username" required="" autofocus="">
    <input type="password" name="password"
      class="form-control" placeholder="Password" required="">
    {{ error }}
    <button class="btn btn-lg btn-primary btn-block" type="submit">
      Log in
    </button>
    {% if is_client %}
    <div class="text-center">
      <a href="/partner/login/">업체용 로그인 하기</a>
    </div>
    {% endif %}
  </form>
</div>
{% endblock %}

templates/main.html
{% extends "base.html" %}
 {% block body %}
   {% include "navbar.html" %}
   <div class="container">
     <div class="row">
       <div class="col-sm-6 col-sm-offset-3">
         <div class="row">
         {% for partner in partner_list %}
           <div class="col-sm-4">
             {% if user.is_authenticated %}
             <a href="/{{ partner.id }}/">
               <h4>{{ partner.name }}</h4>
             </a>
             {% else %}
             <h4>{{ partner.name }}</h4>
             {% endif %}
             <div>{{ partner.address }}</div>
           </div>
         {% endfor %}
         <!--  -->
           <!-- <div class="col-sm-4">
             <h4>호식이</h4>
             <div>서울 은평구</div>
           </div>
           <div class="col-sm-4">
             <h4>호식이</h4>
             <div>서울 은평구</div>
           </div>
           <div class="col-sm-4">
             <h4>호식이</h4>
             <div>서울 은평구</div>
           </div> -->
         <!--  -->
         </div>
       </div>
     </div>
   </div>
 {% endblock %}

templates/menu_add.html
{% extends "base.html" %}
{% block body %}
{% include "navbar.html" %}
<div class="container">
  <div class="col-sm-6 com-sm-offset-3">
    <h2>메뉴 {% if replacement %}{{ replacement }}{% else %}추가{% endif %}하기</h2>
    <form enctype="multipart/form-data" method="post" action="">
      {% csrf_token %}
      <div>
      {{ form }}
      </div>
      <button class="btn btn-default btn-block">
        메뉴 {% if replacement %}{{ replacement }}{% else %}추가{% endif %}하기
      </button>
    </form>
  </div>
</div>
{% endblock %}

templates/menu_detail.html
{% extends "base.html" %}
{% block body %}
{% include "navbar.html" %}
<div class="container">
  <div class="col-sm-6 com-sm-offset-3">
    <table class="table">
      <tr>
        <th>사진</th>
        <td><img style="width:100%" src="{{ menu.image.url }}"></td>
      </tr>
      <tr>
        <th>메뉴 이름</th>
        <td>{{ menu.name }}</td>
      </tr>
      <tr>
        <th>가격</th>
        <td>{{ menu.price }}</td>
      </tr>
    </table>
    <a href="/partner/menu/{{ menu.id }}/edit/">
      <button class="btn btn-default btn-block">수정하기</button>
    </a>
    <a href="/partner/menu/{{ menu.id }}/delete/">
      <button class="btn btn-danger btn-block">삭제</button>
    </a>
  </div>
</div>
{% endblock %}

templates/menu_list.html
{% extends "base.html" %}
{% block body %}
{% include "navbar.html" %}
<div class="container">
  <div class="col-sm-6 com-sm-offset-3">
    <h2>메뉴 입니다.</h2>
    <table class="table">
      <tr>
        <th>이미지</th>
        <th>메뉴 이름</th>
        <th>가격</th>
      </tr>
      {% for menu in menu_list %}
      <tr>
        <td><img style="max-width : 100px;" src="{{ menu.image.url }}"></td>
        <td><a href="/partner/menu/{{ menu.id }}/">{{ menu.name }}</a></td>
        <td>{{ menu.price }}</td>
      </tr>
      {% endfor %}
    </table>
    <a href="/partner/menu/add/">
      <button class="btn btn-default btn-block">메뉴 추가하기</button>
    </a>
  </div>
</div>
{% endblock %}

templates/navbar.html
<nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">배민 따라하기</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/partner/">홈</a></li>
            {% if user.is_authenticated %}
            <li><a href="/partner/menu/">메뉴</a></li>
            <li><a href="/partner/order/">주문</a></li>
            <li><a href="/partner/logout/">로그아웃</a></li>
            {% else %}
            <li><a href="/login/">로그인</a></li>
            <li><a href="/signup/">회원가입</a></li>
            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

templates/order_list_for_partner.html
{% extends "base.html" %}
{% block body %}
{% include "navbar.html" %}
<div class="container">
  <div class="col-sm-6 com-sm-offset-3">
    <h2>주문 입니다.</h2>
    <table class="table">
      <tr>
        <th>고객 이름</th>
        <th>주소</th>
      </tr>
      {% for order in order_set %}
      <tr>
        <td>{{ order.client.name }}</td>
        <td>{{ order.address }}</td>
      </tr>
      {% endfor %}
    </table>
  </div>
</div>
{% endblock %}

templates/order_menu_list.html
{% extends "base.html" %}
{% block body %}
{% include "navbar.html" %}
<div class="container">
  <div class="col-sm-6 col-sm-offset-3">
    <h2>{{partner.name}} 메뉴 입니다.</h2>
    <form action="" method="post">
      {% csrf_token %}
      <table class="table">
        <tr>
          <th>이미지</th>
          <th>메뉴 이름</th>
          <th>가격</th>
          <th>수량</th>
        </tr>
        {% for menu in menu_list %}
        <tr>
          <td><img style="max-width : 100px;" src="{{ menu.image.url }}"></td>
          <td><a href="/partner/menu/{{ menu.id }}/">{{ menu.name }}</a></td>
          <td>{{ menu.price }}</td>
          <td><input name="{{ menu.id }}" value=0 type="number" /></td>
        </tr>
        {% endfor %}
      </table>
      <button class="btn btn-default btn-block" type="submit">주문하기</button>
  </form>
  </div>
</div>
{% endblock %}

templates/signup.html
{% extends "base.html" %}
{% block title %}baemin signup{% endblock %}
{% block body %}
<div class="container">
  <form method="post" action="" class="form-signin">
    {% csrf_token %}
    <h2 class="form-signin-heading">please sign up</h2>
    <input type="text" name="username"
      class="form-control" placeholder="Username" required="" autofocus="">
    <input type="email" name="email"
      class="form-control" placeholder="Email address" required="">
    <input type="password" name="password"
      class="form-control" placeholder="Password" required="">
    <button class="btn btn-lg btn-primary btn-block" type="submit">
      Sign up
    </button>
    {% if is_client %}
    <div class="text-center">
      <a href="/partner/signup/">업체용 회원가입 하기</a>
    </div>
    {% endif %}
  </form>
</div>
{% endblock %}